version: "3.8"

services:
  db:
    image: postgres:14
    env_file:
      - backend/env/postgres.env

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/opt/app
    expose:
      - 5000
    env_file:
      - backend/env/postgres.env
      - backend/env/webapp.env
    depends_on:
      - db

  proxy:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - backend
